import { assets } from './assets.mjs';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const baseline=JSON.parse(assets['/baseline.json'].body);
const focus=['Host SW','AI Model Dev. Tools','Ref. Models','SDK Installer'];
function summary(plan,id,observedAt){const groups={};for(const r of plan.rows){const s=groups[r.section]??={rows:0,tickets:[],statuses:{}};s.rows++;if(r.key&&!s.tickets.includes(r.key))s.tickets.push(r.key);s.statuses[r.status]=(s.statuses[r.status]||0)+1;}return {id,observedAt,sourceModifiedAt:plan.modifiedAt,name:plan.name,rowCount:plan.rows.length,focusRows:plan.rows.filter(r=>focus.includes(r.section)).length,groups};}
const baseSummary=summary(baseline,'baseline',baseline.importedAt||baseline.modifiedAt);
const published=JSON.parse(assets['/source.json'].body);
function dateChanges(before,after,observedAt,runId){const index=rows=>{const m=new Map();for(const r of rows){if(!r.key)continue;const list=m.get(r.key)||[];list.push(r);m.set(r.key,list);}return m;},a=index(before.rows),b=index(after.rows),out=[];for(const [key,rs] of b){const prev=a.get(key);if(rs.length!==1||prev?.length!==1)continue;for(const field of ['preDue','due']){const old=prev[0][field],next=rs[0][field];if(old===next)continue;const dated=x=>/^\d{4}-\d{2}-\d{2}$/.test(x);const days=dated(old)&&dated(next)?Math.round((Date.parse(next)-Date.parse(old))/86400000):null;out.push({key,field,old,new:next,days,kind:!old?'assigned':!next?'cleared':days>0?'slipped':days<0?'pulled-in':'changed',observedAt,runId,currentSection:rs[0].section,source:'workbook snapshot'});}}return out;}
async function seed(db){for(const [id,plan,observed] of [['baseline',baseline,baseSummary.observedAt],['published-'+published.observedAt,published,published.observedAt]]){if(await db.prepare('SELECT id FROM plan_snapshots WHERE id=?').bind(id).first())continue;const previous=await db.prepare('SELECT payload FROM plan_snapshots WHERE observed_at < ? ORDER BY observed_at DESC LIMIT 1').bind(observed).first();const s={...summary(plan,id,observed),hasWorkbook:!!plan.workbookBase64,changes:previous?dateChanges(JSON.parse(previous.payload),plan,observed,id):[]};await db.prepare('INSERT OR IGNORE INTO plan_snapshots(id,observed_at,created_at,source_modified_at,name,row_count,summary,payload) VALUES(?,?,?,?,?,?,?,?)').bind(id,observed,observed,String(plan.modifiedAt||''),plan.name,plan.rows.length,JSON.stringify(s),JSON.stringify(plan)).run();}}
function validatePlan(plan){if(!plan||typeof plan.name!=='string'||typeof plan.sheet!=='string'||!Array.isArray(plan.rows)||plan.rows.length<1||plan.rows.length>2000||!Array.isArray(plan.weeks))throw new Error('Invalid workbook snapshot.');for(const r of plan.rows){if(!Number.isInteger(r.row)||!['section','group','title','team','owner','status','key','due','preDue'].every(k=>typeof r[k]==='string'))throw new Error('Invalid workbook row.');}if(typeof plan.workbookBase64!=='string'||!plan.workbookBase64.startsWith('UEsDB')||plan.workbookBase64.length>1400000)throw new Error('The original workbook is required and must be under 1 MB.');if(!focus.every(s=>plan.rows.some(r=>r.section===s)))throw new Error('Focus sections are missing.');}
async function body(request){if(!request.headers.get('content-type')?.includes('application/json'))throw new Error('JSON is required.');const text=await request.text();if(new TextEncoder().encode(text).length>1900000)throw new Error('Snapshot exceeds the 1.9 MB limit.');return JSON.parse(text);}
export default {async fetch(request,env){const url=new URL(request.url),p=url.pathname;
 try{
  if(p.startsWith('/api/')){
   if(!env.DB)return json({error:'Persistent history is unavailable. Your loaded workbook has not been lost.'},503);
   if(!['GET','HEAD'].includes(request.method)){const origin=request.headers.get('Origin');if(origin&&origin!==url.origin)return json({error:'Cross-origin write rejected.'},403);}
   if(p==='/api/history'&&request.method==='GET'){await seed(env.DB);const [snaps,reviews]=await Promise.all([env.DB.prepare('SELECT summary FROM plan_snapshots ORDER BY observed_at').all(),env.DB.prepare('SELECT id,decision,note,updated_at FROM dependency_reviews').all()]);return json({storage:'ready',snapshots:snaps.results.map(r=>JSON.parse(r.summary)),snapshotChanges:snaps.results.flatMap(r=>JSON.parse(r.summary).changes||[]),reviews:reviews.results});}
   if(p==='/api/snapshots/baseline'&&request.method==='GET')return json(baseline);
   if(p.startsWith('/api/snapshots/')&&request.method==='GET'){const row=await env.DB.prepare('SELECT payload FROM plan_snapshots WHERE id=?').bind(decodeURIComponent(p.split('/').at(-1))).first();return row?json(JSON.parse(row.payload)):json({error:'Snapshot not found.'},404);}
   if(p==='/api/snapshots'&&request.method==='POST'){const {plan}=await body(request);validatePlan(plan);const observedAt=new Date().toISOString(),day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(day+JSON.stringify(plan.rows)+(plan.workbookBase64||'')));const id=[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');const previous=await env.DB.prepare('SELECT payload FROM plan_snapshots ORDER BY observed_at DESC LIMIT 1').first();const s={...summary(plan,id,observedAt),hasWorkbook:!!plan.workbookBase64,changes:previous?dateChanges(JSON.parse(previous.payload),plan,observedAt,id):[]};await env.DB.prepare('INSERT OR IGNORE INTO plan_snapshots(id,observed_at,created_at,source_modified_at,name,row_count,summary,payload) VALUES(?,?,?,?,?,?,?,?)').bind(id,observedAt,observedAt,String(plan.modifiedAt||''),plan.name,plan.rows.length,JSON.stringify(s),JSON.stringify(plan)).run();const saved=await env.DB.prepare('SELECT summary FROM plan_snapshots WHERE id=?').bind(id).first();return json({saved:JSON.parse(saved.summary)},201);}
   if(p==='/api/dependency-review'&&request.method==='POST'){const b=await body(request);const deps=JSON.parse(assets['/dependencies.json'].body).dependencies;if(!deps.some(d=>d.id===b.id)||!['accepted','rejected','unreviewed'].includes(b.decision)||typeof b.note!=='string'||b.note.length>2000)return json({error:'Invalid dependency review.'},400);if(b.decision!=='unreviewed'&&!b.note.trim())return json({error:'Reviewer and evidence are required.'},400);const now=new Date().toISOString();await env.DB.prepare('INSERT INTO dependency_reviews(id,decision,note,updated_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET decision=excluded.decision,note=excluded.note,updated_at=excluded.updated_at').bind(b.id,b.decision,b.note,now).run();return json({id:b.id,decision:b.decision,note:b.note,updated_at:now});}
   return json({error:'Not found.'},404);
  }
  const asset=assets[p==='/'?'/index.html':p];if(!asset)return new Response('Not found',{status:404});return new Response(request.method==='HEAD'?null:asset.body,{headers:{'content-type':asset.type,'cache-control':'no-cache','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'}});
 }catch(error){console.error('Master plan request failed',error.message);return json({error:request.method==='POST'?'The change was not saved. '+error.message:'History could not be loaded. Please retry.'},request.method==='POST'?400:503);}
}};
